# -*- coding: utf-8 -*-
"""comento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HgPYh0IdlcevklLTY9HgxItp4dKScAx1
"""

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.train(data="coco128.yaml", epochs=10, imgsz=640)

from google.colab import files
files.download('/content/runs/detect/train/weights/best.pt')

import matplotlib.pyplot as plt

# 학습된 모델 다시 불러오기 (이미 model 변수가 있으면 안 해도 됨)
metrics = model.val()

# 성능 지표 그래프로 그리기
labels = ["Precision", "Recall", "mAP50", "mAP50-95"]
values = [
    metrics.box.mp,
    metrics.box.mr,
    metrics.box.map50,
    metrics.box.map,
]

plt.figure(figsize=(6, 4))
plt.bar(labels, values, color="skyblue")
plt.ylim(0, 1)
plt.title("YOLO Model Performance")
plt.ylabel("Score")
plt.savefig("model_performance.png")
plt.show()

print("완료! model_performance.png 저장됨")

from google.colab import files
files.download('model_performance.png')